global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  # Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          application: prometheus
          service: prometheus

  # Spring Boot
  - job_name: 'danchu'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app:8080']
        labels:
          application: danchu
          service: app
          component: spring-boot

  # node-exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          application: danchu
          service: node-exporter

  # MySQL
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']
        labels:
          application: danchu
          service: mysql
          component: exporter

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          application: danchu
          service: redis
          component: exporter